### ISSUE TITLE
New docs routing doesn't work

### ISSUE THREAD

**Issue by umidullo** [Telegram-Mini-Apps/issues#13]
Routing of new documentation throws a 404 error when reloading the page

https://docs.telegram-mini-apps.com/about-platform

**Comment by heyqbnk** [comment]
Unfortunately, during transferring the documentation on the other static files provider (Vercel), it seems like DNS records were messed up. The problem should be automatically fixed during this day.

Until then, you can open docs via this link: https://docs-git-master-telegram-mini-apps.vercel.app/

**Comment by umidullo** [comment]
https://docs-git-master-telegram-mini-apps.vercel.app/ routing in this link doesn't work too. I think problem related to redirects

**Comment by heyqbnk** [comment]
This problem should be fixed now. Try this URL:
https://docs.telegram-mini-apps.com/apps-communication/flow-definition

Thanks for report! Let me know if something is still wrong.
