### ISSUE TITLE
The window.Telegram.WebApp.expand() Method Fails to Expand App to Full Height.

### ISSUE THREAD

**Issue by nikitabelotelov-ciliz** [Telegram-Mini-Apps/issues#16]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [x] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug
window.Telegram.WebApp.expand() doesn't expand app to full height. After calling .expand() method, there is a gap between tab header and upper border of the screen. Additionally, it's still possible to drag the tab upwards to increase its height, which indicates that the expansion is not complete.

## To Reproduce

1. Open @nb_bottle_bot from ios
2. Open mini-app by clicking the menu button
3. Click on input, to open OSK
4. Close mini-app
5. Open it again
6. Observe that the app is not expanded to its full height. Notice that while the viewport height appears correct, the entire tab containing the mini-app is positioned lower than it should be. This is further indicated by the ability to drag the tab upwards, which should not be possible.

## Expected behavior
The window.Telegram.WebApp.expand() method is expected to fully expand the mini-app to the maximum available height.

## Video
What happens on the video:
1. Open mini-app from @nb_bottle_bot
2. It expands, but not on full height
3. I drag it to the top
4. It expands to full height

https://github.com/Telegram-Mini-Apps/issues/assets/149486224/e7549bbd-9d3b-444b-a14b-95d394eb6d1d

**Comment by heyqbnk** [comment]
It is rather interesting bug. Could you find a possible explanation why this could happen? I assume, there could be something wrong with the input position absolute and its css bottom property value. Could we increase or decrease it and see if something changed?

**Comment by dontmeway** [comment]
@nikitabelotelov-ciliz hi, did you find any solution or workaround? thanks in advance

**Comment by QumiQumi** [comment]
I found workaround for this. 
You need to set initial window.Telegram.WebApp.isExpanded = false and then expand it:
`window.Telegram.WebApp.isExpanded = false
document.addEventListener("DOMContentLoaded", () => {
  window.Telegram.WebApp.expand();
})
`

**Comment by Nodirbek3d** [comment]
I am having similar issue, it is inconsistent and I have no idea how to debug it. Would be nice to find any workarounds

**Comment by meysamamarlou** [comment]
you forgot to use this 
    `<script src="https://telegram.org/js/telegram-web-app.js"></script>`
in head tag before body

**Comment by meysamamarlou** [comment]
> ## Platform
> Select platforms where this bug is reproducible:
> 
> * [ ]  Telegram for Android
> * [x]  Telegram for iOS
> * [ ]  Telegram for macOS
> * [ ]  Telegram Desktop
> * [ ]  Telegram Web A
> * [ ]  Telegram Web K
> 
> ## Describe the bug
> window.Telegram.WebApp.expand() doesn't expand app to full height. After calling .expand() method, there is a gap between tab header and upper border of the screen. Additionally, it's still possible to drag the tab upwards to increase its height, which indicates that the expansion is not complete.
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Open @nb_bottle_bot from ios
> 2. Open mini-app by clicking the menu button
> 3. Click on input, to open OSK
> 4. Close mini-app
> 5. Open it again
> 6. Observe that the app is not expanded to its full height. Notice that while the viewport height appears correct, the entire tab containing the mini-app is positioned lower than it should be. This is further indicated by the ability to drag the tab upwards, which should not be possible.
> 
> ## Expected behavior
> The window.Telegram.WebApp.expand() method is expected to fully expand the mini-app to the maximum available height.
> 
> ## Video
> What happens on the video:
> 
> 1. Open mini-app from @nb_bottle_bot
> 2. It expands, but not on full height
> 3. I drag it to the top
> 4. It expands to full height
> 
>  2023-12-11.13.55.58.mp4

you forgot to use this
<script src="https://telegram.org/js/telegram-web-app.js"></script>
in head tag before body

> I am having similar issue, it is inconsistent and I have no idea how to debug it. Would be nice to find any workarounds

you too

**Comment by heyqbnk** [comment]
Seems like the issue is not reproducible anymore. Let me know if it still appears
