### ISSUE TITLE
Transfer telegram-mini-apps-dev/awesome-telegram-mini-apps to this org

### ISSUE THREAD

**Issue by roj1512** [Telegram-Mini-Apps/issues#17]
I personally think that telegram-mini-apps/awesome-telegram-mini-apps would be a way catchier name for the awesome list, and would like to have it under that if both sides agree on it.

**Comment by evermake** [comment]
IMHO just `telegram-mini-apps/awesome` would be even better.

**Comment by roj1512** [comment]
The repository name won’t align with Awesome List’s guideline in that case @evermake.

**Comment by heyqbnk** [comment]
Hey. I asked Gleb about this idea and in his mind it isn't really worth it. Nevertheless, in my mind this would be great to create such a repo in this org, but I have no experience and time at the moment to do this. I could create this repo and somebody could fulfil it with required data
