### ISSUE TITLE
Incorrect viewport height on Android devices

### ISSUE THREAD

**Issue by daniilkananenka** [Telegram-Mini-Apps/issues#25]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [x] Telegram for Android
- [ ] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug

I am developing Telegram Mini app using Next.JS framework with App router. I am using @tma.js/sdk-react package. And there is an issue on every Android device. When you open mini app via Menu button, bottom part of it is hidden under user message input. Like on the image, on the left side.

![image](https://github.com/Telegram-Mini-Apps/issues/assets/60035004/c064c266-804a-4251-8e44-77095b78181f)

## To Reproduce

1. Open mini app

## Expected behavior

I want the mini app to open with correct viewport height.
May be I am doing something wrong?

**Comment by heyqbnk** [comment]
What do you mean by "correct viewport height"? What should it be?

**Comment by daniilkananenka** [comment]
Look. When I open the mini-app using the Menu Button inside the bot, the application does not recognize the visible area, and it turns out that part of the application is hidden under the message input field. Here are screenshots of how it works now, and how it should. (Navigation bar is a fixed element)


<img src="https://github.com/Telegram-Mini-Apps/issues/assets/60035004/c590bd1c-00bb-462f-8607-da438a93c142" width="400"/>

<img src="https://github.com/Telegram-Mini-Apps/issues/assets/60035004/2fb17428-5d0e-46a0-b85c-a167d218b4c4" width="400"/>

**Comment by heyqbnk** [comment]
Check if `env(safe-area-inset-bottom)` fits your needs

https://developer.mozilla.org/en-US/docs/Web/CSS/env

**Comment by daniilkananenka** [comment]
I've tried different ways of using env(safe-area-inset-bottom). Both directly in CSS, and through a [special Tailwind plugin](https://github.com/mvllow/tailwindcss-safe-area) and based on [this answer](https://github.com/TelegramMessenger/Telegram-iOS/issues/1377#issuecomment-2085083997). But none of the above works.

Additionally, I noticed the following behavior. When I log into the bot and open the application through the Menu button, part of the application is hidden under the message input field. But if I click on the message input field (the keyboard opens and the Mini app closes), and then re-open the Mini app through the Menu button, then all the problems disappear and the application is displayed in the desired form.

**Comment by daniilkananenka** [comment]
@heyqbnk I just found the solution to my problem. I added the [@twa-dev/sdk](https://github.com/twa-dev/SDK) package and added
```js
useEffect(() => {
  if (typeof window !== 'undefined') {
    WebApp.ready();
  }
}, []);
```
I tried to do the same using `miniApp?.ready()` but it didn't work.(

**Comment by heyqbnk** [comment]
First of all, miniApp.ready() does exactly the same. Secondly, using both Telegram SDK and tma.js in the same app will surely lead to bugs

**Comment by daniilkananenka** [comment]
Yes, I understand. I will try further. In any case, thank you very much for your time😅. 
I think this issue can be closed

**Comment by deadsandro** [comment]
@Kononenko-Daniil 

temporary fix
`postEvent('web_app_setup_main_button', {is_visible: false})` before `miniApp.ready()`

**Comment by daniilkananenka** [comment]
> @Kononenko-Daniil
> 
> temporary fix `postEvent('web_app_setup_main_button', {is_visible: false})` before `miniApp.ready()`

I have already solved this problem. I have added 
`<Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />`. I forgot about it)

**Comment by chang0022** [comment]
@deadsandro Bro, I just found this issue. 🤣 I also found this problem and used the same solution.
I found this code in `telegram-web-app.js`
```
function onThemeChanged(eventType, eventData) {
  if (eventData.theme_params) {
    setThemeParams(eventData.theme_params);
    window.Telegram.WebApp.MainButton.setParams({}); // line: 328
    updateBackgroundColor();
    receiveWebViewEvent('themeChanged');
  }
}
```

**Comment by Sherzod06** [comment]
<img width="523" height="130" alt="Image" src="https://github.com/user-attachments/assets/e13ea66b-9eee-49af-835f-c54a42f4cff8" />

I am also getting this behavior. I am calling tg.expand() when webapp is open. At first everything is fine. But on Samsung devices user can anytime call OneUI's navigation buttons by swiping from bottom. And after that my bottom menu bar is under the OneUI's navigation buttons. What can I do now?
