### ISSUE TITLE
Start web app cut height for old ios devices 

### ISSUE THREAD

**Issue by dobreo** [Telegram-Mini-Apps/issues#29]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [x] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## To Reproduce
 
in iphone 8 or iphone 12 mini, after start webapp, and expand screen by funcion expand(), footer is not showing

and if rotate device - footer coming
![telegram-cloud-photo-size-2-5237989518764795308-y](https://github.com/user-attachments/assets/f8f0fce6-b2c5-41b2-b75d-86b247ed91a1)

**Comment by kanstantsinzanin** [comment]
@dobreo Hey! I've been fighting this bug all day and finally found a fix for it!!! For me helps this solution:

```
import ReactDOM from 'react-dom/client';
import { postEvent } from '@telegram-apps/sdk';
import { Root } from '@/components/Root';

import './mockEnv.ts';
import './index.css';

postEvent('web_app_expand');
postEvent('web_app_setup_main_button', { is_visible: false })
postEvent('web_app_setup_swipe_behavior', { allow_vertical_swipe: false })
postEvent('web_app_ready');

ReactDOM.createRoot(document.getElementById('root')!).render(<Root />);
```

Just moved postEvent('web_app_expand'); from App to index file

**Comment by an-parubets** [comment]
I had the same problem on iPhone X. I found solution for my application.
``` 
html {
	position: fixed;
	height: auto !important;
}
```
