### ISSUE TITLE
Telegram Mini App Android cannot pop up the keyboard after jumping to an external link

### ISSUE THREAD

**Issue by lihongboQ** [Telegram-Mini-Apps/issues#37]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [x] Telegram for Android
- [ ] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug

Telegram Mini App Android cannot pop up the keyboard after jumping to an external link.

## To Reproduce

1.  WebApp.openLink( )

## Expected behavior

Unable to pop up the keyboard when focusing on the input

**Comment by pilip-ton** [comment]
https://github.com/Telegram-Mini-Apps/issues/issues/36 duplicate
