### ISSUE TITLE
TMA  User Counter  Bug

### ISSUE THREAD

**Issue by sunvim** [Telegram-Mini-Apps/issues#40]
## Platform
iOS  and  Andriod

[//]: # (To make as selected, use [x] instead of [ ].)

- [x ] Telegram for Android
- [ x] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug

tma met users show issue, our tma always show 2 users, actually many users,
i read docs about update users, just need user login bot with /start
but we always make user do it like this, our tma users still not update correctly

## To Reproduce

please describe user counter rule clearly

## Expected behavior

user counter correctly

![1](https://github.com/user-attachments/assets/b3005d26-8d6b-4c65-b510-967abcdb2fb6)

**Comment by heyqbnk** [comment]
Not related to Telegram Mini Apps.
