### ISSUE TITLE
Mini Apps - downloads inside apps are not possible

### ISSUE THREAD

**Issue by Prooksius** [Telegram-Mini-Apps/issues#41]
## Select platforms where this bug is reproducible:

- [ x] Telegram for Android
- [ x] Telegram for iOS
- [ ] Telegram for macOS
- [ x] Telegram Desktop
- [ x] Telegram Web A
- [ x] Telegram Web K

## Describe the bug

There is a link in my Mini app, click on it downloads a generated image (qr code) into local file system.
When I open my app by direct link, without telegram - downloading preforms as expected.
When my app is being opened though telegram - download is not being performed.
Tried on all platforms marked [x] above. 

Also tried to debug this situation in telegram web version (Web A). Here is what warning I've got in console:
**"Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details."** 

## Expected behavior

There has to be some setting that allows to download files inside the Mini app.

**Comment by avganka** [comment]
I'm also interested in that point

**Comment by Prooksius** [comment]
I've found some sort of a workaround for downloading in MiniApp. 
It is possible to send images/files to the user through a bot, that is launching my Mini-App.
https://core.telegram.org/bots/api#sendphoto - for images
https://core.telegram.org/bots/api#senddocument - for other files
chat_id is accessible in InitData structure in MiniApp.
The only important thing - it has to be done on the server, not browser, for the security reasons.

**Comment by heyqbnk** [comment]
Implemented since 8.0
