### ISSUE TITLE
Camera access rights are not saved

### ISSUE THREAD

**Issue by f1nked** [Telegram-Mini-Apps/issues#43]
## Platform
- [x] Telegram for Android
- [ ] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug

I am writing an app and I need to access the camera. The desktop version remembers the user's choice, but the mobile version (Android) does not. I haven't had the opportunity to check on iOS yet. Every time the app is opened, it asks for access, which ruins the user experience. How can I fix this? I couldn't find anything about the camera in the documentation.

## Expected behavior

Camera permissions should be retained when you reopen the app.

**Comment by elios-cama** [comment]
Hey, did you find any solution yet? I have the same issue as well on Android only but for the microphone permission, it actually ruins the UX.

**Comment by f1nked** [comment]
> Hey, did you find any solution yet? I have the same issue as well on Android only but for the microphone permission, it actually ruins the UX.

No, I haven't found a solution yet.

**Comment by heyqbnk** [comment]
Could you describe the use case and why this is useful for the whole platform? This will help us to push this feature request forward

**Comment by pilip-ton** [comment]
closing as duplicate with https://github.com/Telegram-Mini-Apps/issues/issues/32
