### ISSUE TITLE
Telegram mini apps are not opening on iphone 6, 6+

### ISSUE THREAD

**Issue by EliasDemlie** [Telegram-Mini-Apps/issues#45]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [ Telegram for iOS ] 
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

**Comment by Saipa12** [comment]
смогли исправить?

**Comment by heyqbnk** [comment]
Please, provide more information on the issue. Until then, closing the issue
