### ISSUE TITLE
We apologize for the inconvenience, but due to a high volume of users on our Telegram mini app, the system is currently experiencing some instability. Please try again later.

### ISSUE THREAD

**Issue by Sufait130** [Telegram-Mini-Apps/issues#47]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [x] Telegram for Android
- [ ] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

**Comment by Sufait130** [comment]
We apologize for the inconvenience, but due to a high volume of users on our Telegram mini app, the system is currently experiencing some instability. Please try again later.

**Comment by Sufait130** [comment]
We apologize for the inconvenience, but due to a high volume of users on our Telegram mini app, the system is currently experiencing some instability. Please try again later.

**Comment by Sufait130** [comment]
We apologize for the inconvenience, but due to a high volume of users on our Telegram mini app, the system is currently experiencing some instability. Please try again later.

Available points
58,930

Your Attempts
0/6
Next attempt in
02:10
Invite Friends for Bonuses
Play Game
Terms and Conditions
Game
Leaderboard
Tasks
Friends
Binance

**Comment by Sufait130** [comment]
We apologize for the inconvenience, but due to a high volume of users on our Telegram mini app, the system is currently experiencing some instability. Please try again later.

Available points
58,930

Your Attempts
0/6
Next attempt in
02:10
Invite Friends for Bonuses
Play Game
Terms and Conditions
Game
Leaderboard
Tasks
Friends
Binance

**Comment by heyqbnk** [comment]
Sometimes this happens. Its ok
