### ISSUE TITLE
WebAppMethodUnsupported when calling any web app method on some users devices

### ISSUE THREAD

**Issue by vladkarataiyardex** [Telegram-Mini-Apps/issues#55]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [x] Telegram for iOS
- [x] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug

**TG version** where bug was initially found: 11.4.269392 AppStore (macOS)
**MacOS version**: macOS Sonoma 14.6.1

![telegram-cloud-photo-size-2-5350719594102383577-x](https://github.com/user-attachments/assets/69ef977a-68af-4261-a4c4-c2eff174d67c)
![telegram-cloud-photo-size-2-5350719594102383585-y](https://github.com/user-attachments/assets/87a90c7b-fc63-4b55-bbad-cdf8b4e4d972)

Some users experiencing WebAppMethodUnsupported error for ANY **window.Telegram.WebApp** method (openTelegramLink, openInvoice). Sometimes (I'd say 30/70) **openTelegramLink** method opens link in browser or just in the next tab from an app. Which is terrible for invite friends logic.

Tg mini app code loads by this script inside auth context (**before** user can somehow interact with app)

```
React.useEffect(() => {
    if (!document.getElementById("script-init-telegram-mini-app")) {
      const newScript = document.createElement("script");

      newScript.src = "https://telegram.org/js/telegram-web-app.js";
      newScript.setAttribute("id", "script-init-telegram-mini-app");
      document.body.append(newScript);

      const loadListener = async () => {
        try {
          const telegramInitData = window.Telegram?.WebApp?.initData || "";
          if (telegramInitData) {
            window.Telegram?.WebApp.ready();
          }
        } catch (e) {
          // ...
        } finally {
            newScript.removeEventListener("load", loadListener);
        }
      };

     newScript.addEventListener("load", loadListener);
    }

  }, [])
```

## To Reproduce

I guess some of testers can experience it in our app (bidpawbot). I personally wasnt able to reproduce it on my side, but getting lots of support messages about this issue.

## Expected behavior

I expect methods to work as described in documentation without errors or non-documented behaviour like opening telegram links in external browser or in next tab is mini apps window.

**Comment by heyqbnk** [comment]
You are not waiting for the script to be loaded.

Also, Telegram SDK requires launch parameters to be in the hash part. I guess, you are just rewriting it using your router and the SDK is unable to retrieve the correct version of the platform.

Try switching to @telegram-apps/sdk-react
