### ISSUE TITLE
Telegram mini app incorrectly reloads Mini App in iphone

### ISSUE THREAD

**Issue by vishnu-zone** [Telegram-Mini-Apps/issues#57]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [ ] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug

 Application abruptly refresh sometime in iphone, how to fix it.

**Comment by heyqbnk** [comment]
Closing due to incorrect issue description.
